### ISSUE TITLE
数据绑定中包含 `<` 报编译错误

### ISSUE THREAD

**Issue by declanqian** [wechat-miniprogram/miniprogram-i18n#19]
一个简单的可以重现的例子

```<view>{{1 < 5 ? true : false}}</view>```

版本
`@miniprogram-i18n/gulp-i18n-wxml": "^1.0.0-rc.8"`

错误信息:
```
error: Error: expected character > to close a tag
    at WxmlParser.parseWxmlTag ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/index.js:481:19)
    at WxmlParser.parse ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/index.js:452:33)
    at WxmlParser.parseWxmlTag ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/index.js:486:31)
    at WxmlParser.parse ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/index.js:452:33)
    at TranslationFunctionTransformer.transform ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/index.js:652:28)
    at DestroyableTransform._transform ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/index.js:752:46)
    at DestroyableTransform.Transform._read ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer ({project}/node_modules/@miniprogram-i18n/gulp-i18n-wxml/node_modules/readable-stream/lib/_stream_writable.js:398:5)
```

**Comment by ele828** [comment]
已经修复，升级到最新版本再试试。
